# Generated by Django 4.1.3 on 2022-11-15 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='img',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='container',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.goods'),
        ),
        migrations.AlterField(
            model_name='container',
            name='port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.port'),
        ),
        migrations.AlterField(
            model_name='user',
            name='manage_port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.port'),
        ),
    ]
